/**
 * lib/auth.js
 * -----------
 * Single-admin JWT session. There is exactly one admin account, sourced from
 * env vars (ADMIN_EMAIL / ADMIN_PASSWORD_HASH) — no admins collection.
 *
 * Session token lives in an httpOnly cookie (COOKIE_NAME), never in
 * localStorage/JS-readable storage, so it can't be read by injected/XSS'd
 * client script.
 *
 * NOTE: uses bcryptjs instead of bcrypt. Same hash format ($2a$/$2b$, fully
 * compatible with hashes generated by bcrypt or bcryptjs interchangeably) —
 * bcryptjs is pure JS with no native build step, which is safer on Vercel's
 * serverless build pipeline than bcrypt's node-gyp compilation.
 */
const jwt = require("jsonwebtoken");
const bcrypt = require("bcryptjs");
const cookie = require("cookie");

const COOKIE_NAME = "admin_token";
const JWT_SECRET = process.env.ADMIN_JWT_SECRET;
const SESSION_DAYS = 7;

function signAdminToken() {
  if (!JWT_SECRET) throw new Error("ADMIN_JWT_SECRET is not set.");
  return jwt.sign({ role: "admin" }, JWT_SECRET, { expiresIn: `${SESSION_DAYS}d` });
}

function verifyAdminToken(token) {
  if (!JWT_SECRET || !token) return null;
  try {
    const payload = jwt.verify(token, JWT_SECRET);
    return payload && payload.role === "admin" ? payload : null;
  } catch {
    return null;
  }
}

async function checkPassword(plain, hash) {
  if (!plain || !hash) return false;
  try {
    return await bcrypt.compare(plain, hash);
  } catch {
    return false;
  }
}

/** Build the Set-Cookie header value for logging in. */
function serializeSessionCookie(token) {
  return cookie.serialize(COOKIE_NAME, token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax",
    path: "/",
    maxAge: SESSION_DAYS * 24 * 60 * 60,
  });
}

/** Build the Set-Cookie header value for logging out (clears the cookie). */
function serializeLogoutCookie() {
  return cookie.serialize(COOKIE_NAME, "", {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax",
    path: "/",
    maxAge: 0,
  });
}

/** Extract + verify the admin session from a raw `Cookie` request header. */
function getAdminFromCookieHeader(cookieHeader) {
  const parsed = cookie.parse(cookieHeader || "");
  return verifyAdminToken(parsed[COOKIE_NAME]);
}

module.exports = {
  COOKIE_NAME,
  signAdminToken,
  verifyAdminToken,
  checkPassword,
  serializeSessionCookie,
  serializeLogoutCookie,
  getAdminFromCookieHeader,
};
